# Default values for IBM® Connect:Direct® for UNIX Helm Chart a.k.a IBM Certified Container Software (IBMCCS).
# This is a YAML-formatted file.
# Declare variables to be passed into your templates. To override the default values either change in this file or use
# --set option provided by helm cli.

# Change license to true to indicate that you have read and agree to license agreements
# Refer: http://www-03.ibm.com/software/sla/sladb.nsf (L/N:  L-MTAE-C5RR2U)
license: false
# Specify the license edition as per license agreement. Valid value is prod or non-prod for Production and 
# Non-production respectively. Remember that this parameter is crucial for IBM Licensing and Metering Service
licenseType: "prod"

# Specify respective timezone 
env:
  timezone: "UTC"

# Add extra labels in addition to default labels to all resources
extraLabels: {}

# Replic number for IBMCCS pod
replicaCount: 1

# Specify the respective Docker Image details for IBMCCS
image:
  # Specify the repository name alongwith image name
  repository: "cp.icr.io/cp/ibm-connectdirect/cdu6.2_certified_container_6.2.0.1"
  # Specify the tag name for the image in double quotes 
  tag: "6.2.0.1_ifix018"
  # Specify the image pull secret for the service, if the image is in private registry 
  # protected with password
  imageSecrets: ""
  # Enable true/false to pull image from Entitled Registry using below digest
  digest:
    enabled: false
    value: "sha256:aa1164cc95bf249b086e167ca318df87da225ca6743fac1f5a48f39bcd061bc7"
  # Specify respective pull policy to used to override default `IfNotPresent` policy 
  pullPolicy: IfNotPresent

nameOverride: ""

# Specify this fields to mount extra volume as volumeMounts in container spec
extraVolumeMounts: []
  #- name:
  #  mountPath: /svshare
# Specify this field to mount extra volume as volumes in the pod spec
extraVolume: []
  #- name: pvc-name
  #  hostPath:
  #    path: /svshare
  #    type: Directory

# Currently, the only supported architecture for IBMCCS is `amd64`
arch: "amd64"

# Specify these fields to provide config values for C:D application  
cdArgs:
  # Specify the node of C:D application
  nodeName: "cdnode"
  # Specify the certificate name to be used for Secure+ configuration
  crtName: ""
  # Specify the client port to be used by C:D application 
  cport: 1363
  # Specify the server port to be used by C:D application
  sport: 1364
  # Specify the name of directory created on persistent volume path having certificate 
  #files need for Secure+ plus configuration
  configDir: "CDFILES"
  # Specify the configuration for SACL options. Refer - https://www.ibm.com/support/knowledgecenter/SS4PJT_6.2.0/cd_unix/cdunix_admin/CDU_Strong_Access_Ctrl_File.html
  saclConfig: "n"

# Specify these fields for C:D Non-Admin user `appuser`
appUser:
  # Specify this to override the default name of Non-Admin user
  name: "appuser"
  # Specify this to set a UID for the Non-Admin user
  uid:
  # Specify this to a GID for the Non-Admin user
  gid: 

# Specify these fields for C:D admin user `cduser`
cduser:
  # Specify this to set a UID for the `cduser`. This is also equivalent to runAsUser security context.
  uid: 45678
  # Specify this to set a GID for the `cduser`. This is also equivalent to `runAsGroup` security context.
  gid: 45678

storageSecurity:
  fsGroup: 45678
  supplementalGroups: [5555]

# persistence section specifies persistence settings which apply to the whole chart
persistence:
  # enabled is whether to use Persistent Volumes or not
  enabled: true
  # useDynamicProvisioning is whether or not to use Storage Classes to dynamically create Persistent Volumes 
  useDynamicProvisioning: false

# Specify these fields for Persistence Volume Claim details
pvClaim:
  # Specify the existing PV claim name to be used for deployment
  existingClaimName: ""
  # Specify this to use any Storage Class for PVC
  storageClassName: ""
  accessMode: "ReadWriteOnce"
  selector:
    # Specify this to use selector label name for PV-PVC bind
    label: ""
    # Specify this to use selector label value for PV-PVC bind
    value: ""
  size: 100Mi

# Specify these fields for Services
service:
  # ClusterPort to be exposed
  type: "LoadBalancer"
  apiport: 
    name: "api"
    port:  
    protocol: "TCP"
  ftport: 
    name: "ft"
    port: 
    protocol: "TCP"
  # List of IP addresses at which the service is available
  # Ref: https://kubernetes.io/docs/user-guide/services/#external-ips
  # E.g -
  # externalIP:
  # - 1.2.3.4
  # - 5.6.7.8
  externalIP: []
  
  # Specify Load Balancer IP, if available
  loadBalancerIP: ""

  # Load Balancer sources
  # https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service
  # E.g -
  # loadBalancerSourceRanges:
  # - 10.10.10.0/24
  loadBalancerSourceRanges: []
  
  # Specify Service Annotations, if required
  annotations: {}

# Specify the Network Policy ingress/egress from and to fields 
# to restrict the traffic from source or by destination
# Ref: https://kubernetes.io/docs/concepts/services-networking/network-policies/
networkPolicy:
  from: []
  # - ipBlock:
  #     cidr: 1.2.0.0/24
  # - podSelector:
  #     matchLabels:
  #       app: "connectdirect"
  to: []
  # - ipBlock:
  #     cidr: 0.0.0.0/0
  #     except:
  #     - 1.2.0.0/14

# Specify the Secret configuration for C:D
secret:
  # Secret name for configuring passwords for C:D
  secretName: ""
  # Secret name of secure plus certificates and LDAP certificates, only needed if Dyanamic Provisioining is Enabled
  certSecretName: ""

# Specify the service account details
serviceAccount:
  # Set this field to `true` to create service account or `false` to use existing service account
  create: true
  # Specify the name of service account to be used 
  name: ""

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  limits:
    cpu: 500m
    memory: 2000Mi
    ephemeral-storage: "5Gi"
  requests:
    cpu: 500m
    memory: 2000Mi
    ephemeral-storage: "3Gi"

# Set this to true to create Monitoring Dashboard for IBMCCS
dashboard:
  enabled: false

affinity:
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity-beta-feature
  # The matchExpression for key 'kubernetes.io/arch' is automatically added based on
  # architecture preference specified in 'arch'
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution: {}
  #   nodeSelectorTerms:
  #   - matchExpressions:
  #     - key: kubernetes.io/e2e-az-name
  #       operator: In
  #       values:
  #       - e2e-az1
  #       - e2e-az2
  # The matchExpression for key 'kubernetes.io/arch' is automatically added based on
  # architecture preference specified in 'arch'
    preferredDuringSchedulingIgnoredDuringExecution: {}

  podAffinity:
    requiredDuringSchedulingIgnoredDuringExecution: {}
    preferredDuringSchedulingIgnoredDuringExecution: {}

  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution: {}
    preferredDuringSchedulingIgnoredDuringExecution: {}

# liveness and Probeness details for the health of pods
livenessProbe:
  initialDelaySeconds: 230
  timeoutSeconds: 30
  periodSeconds: 60

readinessProbe:
  initialDelaySeconds: 220
  timeoutSeconds: 5
  periodSeconds: 60

# Set this field to create route in OpenShift cluster
route:
  enabled: false

# Sepcify these fields to configure ldap support in IBMCCS
ldap:
  # Specify true or false to Enable or Disable LDAP
  enabled: false
  # Specify LDAP server
  host: ""
  # Specify LDAP server port 
  port:
  # Specify the Domain for the LDAP server 
  domain: ""
  # Specify true or false to Enable or Disable TLS authentication
  tls: false
  # Specify CA certificate file name to be used for TLS authentication
  caCert: ""
  # Specify true or false to Enable or Disable TLS authentication on client side
  clientValidation: false
  # Specify client certificate file name to be used for TLS client side authentication
  clientCert: ""
  # Specify client key file name
  clientKey: ""

# Integrated File Agent Configuration
cdfa:
  installFA: "n"
  fileAgentEnable: "n"
